### ISSUE TITLE
Sending value transaction to same address multiple times fails

### ISSUE THREAD

**Issue by stefan-precup** [HelixNetwork/pendulum#182] opened 2019-09-30 16:33 UTC
Expected Behavior
Being able to send multiple value transaction to the same address

Current Behavior
Some times I'm able to send multiple value transaction to the same address. sometimes not

Failure Information (for bugs)
The wallet asks the node for "wereAddressesSpentFrom" and the node returns true even though the address was just generated

Steps to Reproduce
1. Generate address on 2nd account
2. Send value tx from 1st account to 2nd account
3. Repeat step 2 using the same address generated at step 1

Context

I'm using the wallet

Version:
Operating System: Linux

**Comment by adrian-tocu** [comment] 2019-10-01 09:28
The issue is wallet related. Please refer to https://github.com/HelixNetwork/nautilus/issues/30. 
WereAdressSpentFrom is pooling for sender's address. So if the transaction is not confirmed, you will not be able to send again to the same address, until the transaction is confirmed.

**Comment by oliverfn** [comment] 2019-10-27 18:19
Resolved in: https://github.com/HelixNetwork/nautilus/commit/303b987eb093122d2f39ee510d7f2dfe775809ab

**Closed by oliverfn** 2019-10-27 18:19 UTC
Labels: bug
